server:
  host: 0.0.0.0
  port: 8080
  debug: true

target_repository:
  url: "https://github.com/camachoyury/financial-reports"
  branch: "main"
  file_patterns:
    - "**/*.md"
    - "**/*.csv"

agents:
  - name: FinancialAuditWorkflow
    description: "Agente de flujo de trabajo que orquesta el proceso de auditoría financiera"
    tools:
      - run_audit
      - get_audit_summary
  
  - name: DocumentRetrieverAgent
    description: "Agente especializado en recuperar documentos financieros de GitHub"
    tools:
      - retrieve_documents
  
  - name: DocumentParserAgent
    description: "Agente especializado en parsear documentos financieros"
    tools:
      - parse_pl
      - parse_balance
  
  - name: ComparisonAgent
    description: "Agente especializado en comparar documentos financieros"
    tools:
      - compare_documents
  
  - name: IssueManagerAgent
    description: "Agente especializado en gestionar issues de GitHub"
    tools:
      - create_or_update_issue

logging:
  level: INFO
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s" 