version: '3.8'

services:
  auditor:
    build: .
    container_name: financial-auditor
    ports:
      - "8080:8080"
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - GITHUB_REPO_OWNER=camachoyury
      - GITHUB_REPO_NAME=financial-reports
      - GITHUB_BRANCH=main
      - GITHUB_WEBHOOK_SECRET=${GITHUB_WEBHOOK_SECRET}
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/docs"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    command: python -m auditor.agent
